# Generated by Django 5.2.9 on 2025-12-14 02:42

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', jsonfield.fields.JSONField(default=dict)),
            ],
        ),
    ]
