# Generated by Django 5.2.9 on 2025-12-14 03:47

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fields',
        ),
        migrations.AddField(
            model_name='product',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
