# Generated by Django 5.2.9 on 2025-12-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_fields_product_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
